### PR TITLE
Updating GitHub calendar

### PR DESCRIPTION
**Pull request by gvicas17**
## PR TITLE

**Description:** 
Updated to say "no github user info" if person does not provide username rather than saying  "error" 
Added github username to show up above the calendar
  
  
  
  

### Checklist

 * [ ] My code follows the style guidelines of this project
 * [ ] I have performed a self-review of my own code
 * [ ] My code has been reviewed by at least one peer
 * [ ] I have commented my code, particularly in hard-to-understand areas
 * [ ] I have made corresponding changes to the documentation
 * [ ] My changes generate no new warnings
 * [ ] I have added tests that prove my fix is effective or that my feature works
 * [ ] New and existing unit tests pass locally with my changes
 * [ ] There are no merge conflicts

### CODE REVIEW

**Comment by gvicas17** [comment]
I pulled from main before doing any of this and now the profile styling is off. Not sure why.

**Review by Plofland — APPROVED** [review]
Great job

**Comment by robo-chick** [comment]
> I pulled from main before doing any of this and now the profile styling is off. Not sure why.

I notcied this just now, too. There's also an import missing in the dashboard which I can go ahead and add.

**Review by robo-chick — APPROVED** [review]
NM! Saw you added that import. Looks good!

**Pull request merged**
