### PR TITLE
adds modal to create posts in room component

### PR DESCRIPTION
**Pull request by jamesjlundin**
## PR TITLE
**Description:** 
  
Adds button to create a post in room dashboard, and popup modal for post information input and submission, also removes unnecessary fields in postQuestion actions field and axios request
  
So that users can create posts in the room they are viewing
  
They provide the necessary tools to create a post in a room and update the room with the post created
  
Screenshot 2021-02-17 195821

### CODE REVIEW

**Review by jakegrella — APPROVED** [review]
this is exactly what we needed. thank you.

**Comment by jakegrella** [comment]
Just fixed merge conflicts and should be good to go

**Review by salza323 — APPROVED** [review]
Looks awesome.

**Review by s-luong07 — COMMENTED** [review]
Amazing Job James !

**Pull request merged**
