### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by jakegrella**
PR template was previously added for backend, now being added for frontend too. Will autopopulate when a PR is started.

### CODE REVIEW

**Comment by yvette-luong** [comment]
Thank you Jake.

**Review by jamesjlundin — APPROVED** [review]
this will definitely make it easier to provide useful information in all our PR and commits and provide a template for developers who may not know what to include

**Review by JustinMrks — APPROVED** [review]
Template looks correctly formatted

**Comment by s-luong07** [comment]
`Great works on formatting information. Thank you Jake`

**Pull request merged**
