### PR TITLE
Feature/delete user account fe

### PR DESCRIPTION
**Pull request by salza323**
This branch contains:
-added a delete handler to the settings.js file to deactivate account and uses Axios to send the delete request to BE, useHistory to push the user back to '/' when the user account is deactivated.

### CODE REVIEW

**Comment by s-luong07** [comment]
Great job Sal !

**Review by jamesjlundin — APPROVED** [review]
the formatting changes are in line with the projects formatting plans and the axios request to delete user is working functionally.

**Review by JustinMrks — APPROVED** [review]
Delete request looks good, will need to update endpoints to use heroku once fully functional

**Review by jakegrella — APPROVED** [review]
formatting really messed with this one, huh... looks good otherwise

**Pull request merged**
